In [1]:
import os
import cv2
import numpy as np

In [2]:
IMAGE_SIZE = (100,100)
NUM_EIGENFACES = 6
DATASET_PATH = "input"

In [3]:
#creating training matrix, each detected face is covered as vector
# if face image is 100*100, D = 100*100 =10000
def load_images(dataset_path):
    images =[]
    labels =[]
    label_map ={}
    label_id =0
    for filename in os.listdir(dataset_path):
        filepath = os.path.join(dataset_path, filename)
        print("filepath:", filepath)
        print("filename:", filename)
        if os.path.isfile(filepath):
            print("img_path:", filepath)
            img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, IMAGE_SIZE)
            images.append(img.flatten())
            labels.append(label_id)
        label_id +=1
    return np.array(images), np.array(labels), label_map
    # for person in os.listdir(dataset_path):
    #     person_path = os.path.join(dataset_path, person)
    #     if not os.path.isdir(person_path):
    #         continue
    #     label_map[label_id] = person
    #     for image_name in os.listdir(person_path):
            #img_path = os.path.join(filepath, filename)
           
X, Y, label_map = load_images(DATASET_PATH)
X =X.astype(np.float32)
print("Training Images:", X.shape)

filepath: output\1.JPG
filename: 1.JPG
img_path: output\1.JPG
filepath: output\10.JPG
filename: 10.JPG
img_path: output\10.JPG
filepath: output\100.JPG
filename: 100.JPG
img_path: output\100.JPG
filepath: output\101.JPG
filename: 101.JPG
img_path: output\101.JPG
filepath: output\102.JPG
filename: 102.JPG
img_path: output\102.JPG
filepath: output\103.JPG
filename: 103.JPG
img_path: output\103.JPG
filepath: output\11.JPG
filename: 11.JPG
img_path: output\11.JPG
filepath: output\12.JPG
filename: 12.JPG
img_path: output\12.JPG
filepath: output\13.JPG
filename: 13.JPG
img_path: output\13.JPG
filepath: output\14.JPG
filename: 14.JPG
img_path: output\14.JPG
filepath: output\15.JPG
filename: 15.JPG
img_path: output\15.JPG
filepath: output\16.JPG
filename: 16.JPG
img_path: output\16.JPG
filepath: output\17.JPG
filename: 17.JPG
img_path: output\17.JPG
filepath: output\18.JPG
filename: 18.JPG
img_path: output\18.JPG
filepath: output\19.JPG
filename: 19.JPG
img_path: output\19.JPG
filepath: output

In [4]:
#Mean Faces
mean_faces = np.mean(X, axis=0)
#Mean centering
A = X- mean_faces

In [5]:
A.shape

(102, 10000)

In [6]:
# covariance matrix size
L = np.dot(A, A.T)

In [7]:
L

array([[ 48829060.  ,  12450508.  ,   3841930.8 , ...,   -548638.56,
        -16730379.  ,    201270.53],
       [ 12450508.  ,  47925236.  ,   6384456.  , ...,   5040368.  ,
        -20263362.  ,   3295415.8 ],
       [  3841930.8 ,   6384456.  ,  17854596.  , ...,    996758.8 ,
         -3705431.8 ,   4074536.2 ],
       ...,
       [  -548638.56,   5040368.  ,    996758.8 , ...,  25523634.  ,
          4881100.  ,  -6071691.5 ],
       [-16730379.  , -20263362.  ,  -3705431.8 , ...,   4881100.  ,
         44635792.  ,  -9959570.  ],
       [   201270.53,   3295415.8 ,   4074536.2 , ...,  -6071691.5 ,
         -9959570.  ,  24540226.  ]], dtype=float32)

In [8]:
eigenvalues, eigenvectors = np.linalg.eigh(L)

In [9]:
#eigenvalues.sort()

In [10]:
#eigenvalues = eigenvalues[::-1]

In [11]:
eigenvectors

array([[ 0.09901502, -0.0557704 ,  0.0612397 , ..., -0.09317219,
        -0.05494377,  0.17997232],
       [ 0.09901494, -0.07428625,  0.06814421, ..., -0.12257433,
         0.04925385,  0.07775596],
       [ 0.09901488,  0.01020433,  0.02421195, ...,  0.04204033,
        -0.01178526,  0.0238985 ],
       ...,
       [ 0.0990146 , -0.0024674 ,  0.06700806, ..., -0.11502116,
        -0.02534649, -0.027616  ],
       [ 0.09901466,  0.0208603 ,  0.06745864, ...,  0.02860369,
        -0.15485892, -0.14607285],
       [ 0.09901483,  0.06704316,  0.00341833, ...,  0.14205334,
         0.06453239,  0.04063832]], dtype=float32)

In [12]:
eigenvectors[:, :20]

array([[ 0.09901502, -0.0557704 ,  0.0612397 , ..., -0.15512387,
        -0.2416    ,  0.08038823],
       [ 0.09901494, -0.07428625,  0.06814421, ..., -0.02577351,
        -0.06163617, -0.19076797],
       [ 0.09901488,  0.01020433,  0.02421195, ..., -0.10843234,
        -0.16649924,  0.06158539],
       ...,
       [ 0.0990146 , -0.0024674 ,  0.06700806, ...,  0.06291429,
         0.05712752,  0.08512811],
       [ 0.09901466,  0.0208603 ,  0.06745864, ...,  0.18328251,
        -0.21396871,  0.15985876],
       [ 0.09901483,  0.06704316,  0.00341833, ...,  0.04839791,
        -0.02431147, -0.0084697 ]], dtype=float32)

In [13]:
# eigen faces are principle components of face variance 
idx = np.argsort(-eigenvalues)
eigenvectors = eigenvectors[:,idx]
eigenfaces = np.dot(A.T, eigenvectors[:, :NUM_EIGENFACES])
#eigenfaces = eigenfaces[:, :NUM_EIGENFACES]

In [14]:
eigenfaces

array([[-478.2727  ,  148.82259 , -133.0597  ,  128.75531 ,  -32.088924,
          36.256104],
       [-479.6422  ,  171.63757 , -150.3958  ,  100.62548 ,  -27.244513,
          44.34055 ],
       [-480.4521  ,  172.41325 , -154.60754 ,  110.78499 ,  -23.055784,
          54.92309 ],
       ...,
       [-260.47675 , -187.2954  ,  222.9647  ,   71.76203 ,  -66.29844 ,
         -96.26765 ],
       [-290.54694 , -179.0838  ,  244.13771 ,   45.393253,  -70.51227 ,
         -95.74154 ],
       [-314.16498 , -205.77919 ,  248.1719  ,  -33.171673,  -66.00699 ,
        -117.41038 ]], dtype=float32)

In [15]:
for i in range(NUM_EIGENFACES):
    eigenfaces[:, i]= eigenfaces[:, i]/ np.linalg.norm(eigenfaces[:,i])
    #print(eigenfaces[:, 18])

In [16]:
eigenfaces.shape

(10000, 6)

In [17]:
train_features = np.dot(A, eigenfaces)

In [18]:
train_features

array([[ 5.02316553e+03, -1.12790564e+03, -1.34290747e+03,
         6.21662170e+02, -8.40237427e+02,  1.53866040e+03],
       [ 2.17022852e+03,  1.01110126e+03, -1.76668579e+03,
        -3.42265088e+03, -2.55201489e+03,  2.81133209e+02],
       [ 6.67025452e+02, -2.41932037e+02,  6.05934753e+02,
        -1.02853259e+03, -9.30320862e+02,  5.99971680e+02],
       [ 2.50503345e+03, -6.24648010e+02, -6.28999176e+01,
        -1.15276892e+03,  6.53654724e+02, -9.36116180e+01],
       [-5.20809204e+02, -3.30758252e+03, -5.66132446e+02,
         1.70726288e+02,  1.29343674e+02,  1.88213654e+02],
       [ 1.12617017e+03,  2.92598047e+03,  8.97519897e+02,
         6.58025513e+02, -1.00808234e+03,  2.50404443e+03],
       [ 4.49743896e+03, -1.72397815e+03,  1.22964502e+03,
        -3.65243677e+03,  3.94146606e+02, -9.68599987e+00],
       [ 4.95483008e+03, -6.28472900e+02, -5.88095581e+02,
         2.06852515e+03, -7.60955505e+02,  7.44817017e+02],
       [-3.55743970e+03,  3.16487256e+03, -1.813

In [19]:
def recognize(image_path, threshold=3000):
    face = detect_face(image_path)
    print(face)
    print(face.shape)
    if face is None:
        return "No face detected"
    face = face.flatten().astype(np.float32)
    print(face.shape)
    print(mean_faces.shape)
    face_centered = face- mean_faces
    test_features = np.dot(face_centered, eigenfaces)
    print("train features", train_features)
    print("test features", test_features)
    distances = np.linalg.norm(train_features - test_features, axis=1)
    print("distances:",distances)
    min_index = np.argmin(distances)
    print(min_index)
    if distances[min_index] > threshold:
        return "Unknown"
    return distances[min_index]


In [20]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")

In [21]:
def detect_face(image_path, size=(100,100)):
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=5)
    if len(faces) == 0:
        return None
    x,y, w, h = faces[0]
    face = gray[y:y+h, x:x+w]
    face = cv2.resize(face, size)
    return face
    

In [22]:


result = recognize("output/7.jpg")
print(result)

[[  8  11  10 ...  29  19  19]
 [ 11  14  13 ...  21  24  15]
 [  9   9   8 ...  33  22  18]
 ...
 [101  36  13 ...   6   8  10]
 [ 80  50  12 ...   8  10  10]
 [ 19   7   4 ...   9  12  15]]
(100, 100)
(10000,)
(10000,)
train features [[ 5.02316553e+03 -1.12790564e+03 -1.34290747e+03  6.21662170e+02
  -8.40237427e+02  1.53866040e+03]
 [ 2.17022852e+03  1.01110126e+03 -1.76668579e+03 -3.42265088e+03
  -2.55201489e+03  2.81133209e+02]
 [ 6.67025452e+02 -2.41932037e+02  6.05934753e+02 -1.02853259e+03
  -9.30320862e+02  5.99971680e+02]
 [ 2.50503345e+03 -6.24648010e+02 -6.28999176e+01 -1.15276892e+03
   6.53654724e+02 -9.36116180e+01]
 [-5.20809204e+02 -3.30758252e+03 -5.66132446e+02  1.70726288e+02
   1.29343674e+02  1.88213654e+02]
 [ 1.12617017e+03  2.92598047e+03  8.97519897e+02  6.58025513e+02
  -1.00808234e+03  2.50404443e+03]
 [ 4.49743896e+03 -1.72397815e+03  1.22964502e+03 -3.65243677e+03
   3.94146606e+02 -9.68599987e+00]
 [ 4.95483008e+03 -6.28472900e+02 -5.88095581e+02  2.0685

In [23]:
result = recognize("output/8.JPG")
print(result)

[[148 148 149 ...  28  27  30]
 [151 151 150 ...  26  27  28]
 [152 152 151 ...  25  27  26]
 ...
 [152 154 152 ...  29  36  27]
 [152 155 152 ...  28  34  24]
 [153 155 155 ...  30  35  26]]
(100, 100)
(10000,)
(10000,)
train features [[ 5.02316553e+03 -1.12790564e+03 -1.34290747e+03  6.21662170e+02
  -8.40237427e+02  1.53866040e+03]
 [ 2.17022852e+03  1.01110126e+03 -1.76668579e+03 -3.42265088e+03
  -2.55201489e+03  2.81133209e+02]
 [ 6.67025452e+02 -2.41932037e+02  6.05934753e+02 -1.02853259e+03
  -9.30320862e+02  5.99971680e+02]
 [ 2.50503345e+03 -6.24648010e+02 -6.28999176e+01 -1.15276892e+03
   6.53654724e+02 -9.36116180e+01]
 [-5.20809204e+02 -3.30758252e+03 -5.66132446e+02  1.70726288e+02
   1.29343674e+02  1.88213654e+02]
 [ 1.12617017e+03  2.92598047e+03  8.97519897e+02  6.58025513e+02
  -1.00808234e+03  2.50404443e+03]
 [ 4.49743896e+03 -1.72397815e+03  1.22964502e+03 -3.65243677e+03
   3.94146606e+02 -9.68599987e+00]
 [ 4.95483008e+03 -6.28472900e+02 -5.88095581e+02  2.0685

# ========PCA Face Recognization========

In [24]:
import cv2
import numpy as np
import os
from sklearn.decomposition import PCA
from PIL import Image

In [25]:
from sklearn import decomposition
from sklearn.preprocessing import LabelEncoder

In [26]:
IMAGE_SIZE = (100, 100)
N_COMPONENTS = 10
directory_path = 'face_recog/'

In [27]:
smallest_image = None
smallest_size = None
smallest_dims = None
for person in os.listdir(directory_path):
    person_path = os.path.join(directory_path, person)
    if not os.path.isdir(person_path):
        continue
    for filename in os.listdir(person_path):
        filepath = os.path.join(person_path, filename)
        if os.path.isfile(filepath):
            img = Image.open(filepath)
            width, height = img.size
            area = width * height
            if smallest_size is None or area < smallest_size:
                smallest_size = area
                smallest_image = filepath
                smallest_dims = (width, height)
print("Smallest image:", smallest_image)
print("Size (width, height):", smallest_dims)
print("Total pixels:", smallest_size)

Smallest image: face_recog/samantha\1.JPG
Size (width, height): (120, 142)
Total pixels: 17040


In [28]:
for person in os.listdir(directory_path):
        person_path = os.path.join(directory_path, person)
        if not os.path.isdir(person_path):
            continue
        for filename in os.listdir(person_path):
            filepath = os.path.join(person_path, filename)
            if os.path.isfile(filepath):
                filename = os.path.basename(filepath)
                img = Image.open(filepath)
                img_array = np.array(img)
                #output_img = np.zeros(img_array.shape, dtype=np.int64)
                output_array = np.zeros_like(img_array)
                height, width, channels = img_array.shape
                for i in range(height):
                    for j in range(width):
                        avg_value = int(np.mean(img_array[i, j]))
                        for c in range(channels):
                            output_array[i, j, c] = avg_value
                output_img = Image.fromarray(output_array)
                resized_img = output_img.resize(smallest_dims, Image.LANCZOS)
                resized_img.save(person_path+"/"+filename)

In [29]:
def load_faces(dataset_path):
    faces = []
    labels = []

    for person in os.listdir(dataset_path):
        person_path = os.path.join(dataset_path, person)
        if not os.path.isdir(person_path):
            continue
        for img_name in os.listdir(person_path):
            img_path = os.path.join(person_path, img_name)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            if img is None:
                continue
            img = cv2.resize(img, IMAGE_SIZE)
            faces.append(img.flatten())
            labels.append(person)
    return np.array(faces), np.array(labels)


In [30]:
### print("[INFO] Loading training data...")
X, y = load_faces(directory_path)

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("[INFO] Training PCA model...")
pca = PCA(n_components=N_COMPONENTS, whiten=True)
X_pca = pca.fit_transform(X)


[INFO] Training PCA model...


In [31]:
# -----------------------------
# COMPUTE THRESHOLD
# -----------------------------
print("[INFO] Computing threshold...")
intra_distances = []

for i in range(len(X_pca)):
    for j in range(len(X_pca)):
        if y_encoded[i] == y_encoded[j] and i != j:
            d = np.linalg.norm(X_pca[i] - X_pca[j])
            intra_distances.append(d)

intra_distances = np.array(intra_distances)
THRESHOLD = np.mean(intra_distances) + 2 * np.std(intra_distances)

print(f"[INFO] Threshold value: {THRESHOLD:.2f}")

[INFO] Computing threshold...
[INFO] Threshold value: 4.94


In [32]:
# -----------------------------
# FACE RECOGNITION FUNCTION
# -----------------------------
def recognize_face(test_image_path):
    img = cv2.imread(test_image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise ValueError("Test image not found")

    img = cv2.resize(img, IMAGE_SIZE)
    test_vector = img.flatten()

    # Project test image into PCA space
    test_pca = pca.transform([test_vector])

    # Compute Euclidean distances
    distances = np.linalg.norm(X_pca - test_pca, axis=1)

    min_index = np.argmin(distances)
    min_distance = distances[min_index]
    predicted_label = y_encoded[min_index]

    name = label_encoder.inverse_transform([predicted_label])[0]

    return name, min_distance

In [33]:
# -----------------------------
# TEST IMAGE
# -----------------------------
print("[INFO] Testing image...")
img = Image.open("face_recog/sneha.JPG")
img_array = np.array(img)
output_array = np.zeros_like(img_array)
height, width, channels = img_array.shape
for i in range(height):
    for j in range(width):
        avg_value = int(np.mean(img_array[i, j]))
        for c in range(channels):
            output_array[i, j, c] = avg_value
output_img = Image.fromarray(output_array)
resized_img = output_img.resize(smallest_dims, Image.LANCZOS)
resized_img.save("face_recog/sneha_b.JPG")
test_image_path = "face_recog/sneha_b.JPG"

name, distance = recognize_face(test_image_path)

print(f"Predicted: {name}")
print(f"Distance : {distance:.2f}")

if distance < THRESHOLD:
    print("✅ Face Recognized")
else:
    print("❌ Unknown Face")

[INFO] Testing image...
Predicted: samantha
Distance : 2.78
✅ Face Recognized


In [34]:
print("[INFO] Testing image...")
img = Image.open("face_recog/samantha.JPG")
img_array = np.array(img)
output_array = np.zeros_like(img_array)
height, width, channels = img_array.shape
for i in range(height):
    for j in range(width):
        avg_value = int(np.mean(img_array[i, j]))
        for c in range(channels):
            output_array[i, j, c] = avg_value
output_img = Image.fromarray(output_array)
resized_img = output_img.resize(smallest_dims, Image.LANCZOS)
resized_img.save("face_recog/samantha_b.JPG")
test_image_path = "face_recog/samantha_b.JPG"

name, distance = recognize_face(test_image_path)

print(f"Predicted: {name}")
print(f"Distance : {distance:.2f}")

if distance < THRESHOLD:
    print("✅ Face Recognized")
else:
    print("❌ Unknown Face")

[INFO] Testing image...
Predicted: sneha
Distance : 3.05
✅ Face Recognized


In [35]:
print("[INFO] Testing image...")
img = Image.open("face_recog/pooja_hegde.JPG")
img_array = np.array(img)
output_array = np.zeros_like(img_array)
height, width, channels = img_array.shape
for i in range(height):
    for j in range(width):
        avg_value = int(np.mean(img_array[i, j]))
        for c in range(channels):
            output_array[i, j, c] = avg_value
output_img = Image.fromarray(output_array)
resized_img = output_img.resize(smallest_dims, Image.LANCZOS)
resized_img.save("face_recog/pooja_hegde_b.JPG")
test_image_path = "face_recog/pooja_hegde_b.JPG"

name, distance = recognize_face(test_image_path)

print(f"Predicted: {name}")
print(f"Distance : {distance:.2f}")

if distance < THRESHOLD:
    print("✅ Face Recognized")
else:
    print("❌ Unknown Face")

[INFO] Testing image...
Predicted: sneha
Distance : 2.05
✅ Face Recognized


In [36]:
print("[INFO] Testing image...")
img = Image.open("face_recog/1.JPG")
img_array = np.array(img)
output_array = np.zeros_like(img_array)
height, width, channels = img_array.shape
for i in range(height):
    for j in range(width):
        avg_value = int(np.mean(img_array[i, j]))
        for c in range(channels):
            output_array[i, j, c] = avg_value
output_img = Image.fromarray(output_array)
resized_img = output_img.resize(smallest_dims, Image.LANCZOS)
resized_img.save("face_recog/1_b.JPG")
test_image_path = "face_recog/1_b.JPG"

name, distance = recognize_face(test_image_path)

print(f"Predicted: {name}")
print(f"Distance : {distance:.2f}")

if distance < THRESHOLD:
    print("✅ Face Recognized")
else:
    print("❌ Unknown Face")

[INFO] Testing image...
Predicted: sneha
Distance : 2.71
✅ Face Recognized


In [37]:
print("[INFO] Testing image...")
img = Image.open("face_recog/2.JPG")
img_array = np.array(img)
output_array = np.zeros_like(img_array)
height, width, channels = img_array.shape
for i in range(height):
    for j in range(width):
        avg_value = int(np.mean(img_array[i, j]))
        for c in range(channels):
            output_array[i, j, c] = avg_value
output_img = Image.fromarray(output_array)
resized_img = output_img.resize(smallest_dims, Image.LANCZOS)
resized_img.save("face_recog/2_b.JPG")
test_image_path = "face_recog/2_b.JPG"

name, distance = recognize_face(test_image_path)

print(f"Predicted: {name}")
print(f"Distance : {distance:.2f}")

if distance < THRESHOLD:
    print("✅ Face Recognized")
else:
    print("❌ Unknown Face")

[INFO] Testing image...
Predicted: sneha
Distance : 2.65
✅ Face Recognized


In [38]:
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

def detect_face(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    return faces


In [39]:
img = cv2.imread("face_recog/pooja_hegde_b.JPG")
faces = detect_face(img)

if len(faces) == 0:
    print("❌ No face detected")
    #exit()


In [40]:
# FIX #2: Reconstruction Error
def reconstruction_error(test_vector):
    projected = pca.transform([test_vector])
    reconstructed = pca.inverse_transform(projected)
    error = np.linalg.norm(test_vector - reconstructed[0])
    return error


In [41]:
recon_errors = []
for x in X:
    err = reconstruction_error(x)
    recon_errors.append(err)
RECON_THRESHOLD = np.mean(recon_errors) + 2 * np.std(recon_errors)

In [42]:
RECON_THRESHOLD

2122.6385919394324

In [51]:
identity_distances = []

for i in range(len(X_pca)):
    for j in range(len(X_pca)):
        if y_encoded[i] == y_encoded[j] and i != j:
            d = np.linalg.norm(X_pca[i] - X_pca[j])
            identity_distances.append(d)

identity_distances = np.array(identity_distances)

IDENTITY_THRESHOLD = (
    np.mean(identity_distances) + 2 * np.std(identity_distances)
)

print("IDENTITY_THRESHOLD:", IDENTITY_THRESHOLD)

IDENTITY_THRESHOLD: 4.937153330938257


In [54]:
img = cv2.imread("face_recog/sneha_b.JPG", cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, IMAGE_SIZE)
test_vector = img.flatten()
recon_err = reconstruction_error(test_vector)
print(recon_err)
print(RECON_THRESHOLD)
if recon_err > RECON_THRESHOLD:
    print("❌ Not a face")
else:
    name, dist = recognize_face("face_recog/sneha_b.JPG")
    if dist < IDENTITY_THRESHOLD:
        print("✅ Face recognized as", name)
    else:
        print("⚠️ Face detected but unknown person")

4890.382598613049
2122.6385919394324
❌ Not a face
